name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm --workspace=packages/butlerov ci
      - run: npm --workspace=packages/butlerov test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm --workspace=packages/butlerov ci
      - run: npm --workspace=packages/butlerov publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
